name: Build

on:
  push:
    branches: [lunar/main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    name: Deploy

    steps:
      - name: Checkout from GitHub
        uses: actions/checkout@master

      - name: Configure Google Cloud credentials
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/271010089174/locations/global/workloadIdentityPools/github/providers/github-oidc'
          service_account: 'github-actions@moonsworth-299m4oir.iam.gserviceaccount.com'

      - name: Use JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build
        run: ./gradlew publish
